apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-backend
  template:
    metadata:
      labels:
        app: crud-backend
    spec:
      containers:
        - name: app
          image: crud-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:                  # Minimum resources needed
              memory: "64Mi"           # 64 megabytes of RAM
              cpu: "50m"               # 5% of one CPU core
            limits:                    # Maximum resources allowed
              memory: "128Mi"          # 128 megabytes of RAM
              cpu: "100m"              # 10% of one CPU core
          #Health checks
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5    # Time to wait before starting health checks
            periodSeconds: 10   #Check every 10 seconds